# Generated by Django 3.2.8 on 2022-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50)),
                ('place_review_score', models.CharField(max_length=30)),
                ('place_review_visit', models.IntegerField()),
                ('place_review_blog', models.IntegerField()),
                ('place_location', models.CharField(blank=True, max_length=100, null=True)),
                ('place_subway', models.CharField(blank=True, max_length=100, null=True)),
                ('place_time', models.CharField(blank=True, max_length=300, null=True)),
                ('place_imageurl', models.URLField(blank=True, null=True)),
                ('place_register', models.DateTimeField(null=True)),
            ],
        ),
    ]
