# Generated by Django 3.2.8 on 2022-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=100),
        ),
    ]
