# Generated by Django 3.2.8 on 2022-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_info',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
