# Generated by Django 3.2.8 on 2022-01-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_place_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
