# Generated by Django 3.2.8 on 2022-01-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_place_place_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_review_blog',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_review_score',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_review_visit',
            field=models.IntegerField(null=True),
        ),
    ]
