# Generated by Django 3.2.8 on 2022-01-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20220124_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_review_blog',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_review_visit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
