# Generated by Django 3.2.8 on 2022-01-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.location'),
        ),
    ]
