# Generated by Django 3.2.8 on 2022-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_alter_place_place_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_imageurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
