# Generated by Django 3.2.8 on 2022-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_alter_place_place_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_sns_site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
