# Generated by Django 3.2 on 2022-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여', 'female'), ('남', 'male')], max_length=20),
        ),
    ]
